"""
Abstract interfaces and architecture specifications for the future Blind ANN Watermark Extractor.

STATUS: PLANNED / IN PROGRESS
The deep neural network for blind watermark extraction without original host images
is NOT yet implemented in this repository.

This module establishes the exact model input/output contract, hyperparameter configuration,
and base classes for seamless future integration.
"""
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, Tuple
import numpy as np


class BaseANNWatermarkExtractor(ABC):
    """
    Abstract Base Class for future Deep Learning Blind Watermark Extractors.
    
    Contract:
    - Input: Attacked / Watermarked Image or I-Channel of shape (B, 1, 256, 256)
             WITHOUT access to the clean host image (Blind Extraction).
    - Output: Predicted watermark array of shape (B, 1, 32, 32) in range [0, 1].
    """

    def __init__(self, model_name: str = "BlindExtractorPlaceholder"):
        self.model_name = model_name
        self.is_trained = False

    @abstractmethod
    def forward(self, input_tensor: Any) -> Any:
        """Forward pass through the neural network."""
        pass

    @abstractmethod
    def extract_blind(self, watermarked_channel: np.ndarray) -> np.ndarray:
        """
        Inference interface:
        Given an unknown watermarked 256x256 image channel without host,
        predict and output the 32x32 binary watermark.
        """
        pass

    @abstractmethod
    def save_checkpoint(self, path: str) -> None:
        """Save network weights to disk."""
        pass

    @abstractmethod
    def load_checkpoint(self, path: str) -> None:
        """Load network weights from disk."""
        pass


class PlannedANNModelPlaceholder(BaseANNWatermarkExtractor):
    """
    Concrete placeholder representing the unbuilt ANN Extractor.
    Ensures that calling unbuilt ANN phases raises clear, honest status messages.
    """

    def __init__(self):
        super().__init__(model_name="PlannedANNModelPlaceholder")

    def forward(self, input_tensor: Any) -> Any:
        raise NotImplementedError(
            "PLANNED — ANN blind extractor architecture is not yet implemented. "
            "Please train the model once the network weights and architecture are constructed."
        )

    def extract_blind(self, watermarked_channel: np.ndarray) -> np.ndarray:
        raise NotImplementedError(
            "PLANNED — Blind ANN extraction requires trained neural network weights. "
            "Currently only Non-Blind (Host-Subtracted) extraction is implemented."
        )

    def save_checkpoint(self, path: str) -> None:
        raise NotImplementedError("PLANNED — Checkpoint saving pending model implementation.")

    def load_checkpoint(self, path: str) -> None:
        raise NotImplementedError("PLANNED — Checkpoint loading pending model implementation.")


def get_ann_model_info() -> Dict[str, Any]:
    """Return implementation status and architecture metadata for reports."""
    return {
        "status": "PLANNED",
        "description": "Blind Deep Neural Network Watermark Extractor (Host-Free)",
        "input_shape": [1, 256, 256],
        "output_shape": [1, 32, 32],
        "loss_function": "BCE / MSE Hybrid",
        "notes": "Pending Phase 3 research implementation. Training pairs are generated by Phase 8."
    }
